// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Shared.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "6b62dec5-1437-4827-bca1-f49800d30789",
                            Description = "Product 1 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/1/500",
                            Price = 1000L,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = "da993c4d-028f-4653-a2b8-2eb54ad872dd",
                            Description = "Product 2 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/2/500",
                            Price = 2000L,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = "90c4c915-6720-445e-a642-17884348db68",
                            Description = "Product 3 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/3/500",
                            Price = 3000L,
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = "9d0c414d-e322-493f-81f3-d1e72067db9b",
                            Description = "Product 4 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/4/500",
                            Price = 4000L,
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = "28b9876c-7422-476b-96b6-6d4a6fc98b52",
                            Description = "Product 5 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/5/500",
                            Price = 5000L,
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = "fde74c4c-f525-4e71-8c3e-2b6e623ef618",
                            Description = "Product 6 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/6/500",
                            Price = 6000L,
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = "8b967a59-714d-47d3-9fe8-0207ccdf829b",
                            Description = "Product 7 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/7/500",
                            Price = 7000L,
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = "e5d8f50f-2615-495e-aa4f-4c3c19cc7db6",
                            Description = "Product 8 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/8/500",
                            Price = 8000L,
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = "5cc7a856-4f22-4f2d-9778-bb4752bf6182",
                            Description = "Product 9 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/9/500",
                            Price = 9000L,
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = "363dec49-5f75-447b-a14e-f5bca894e101",
                            Description = "Product 10 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/10/500",
                            Price = 10000L,
                            Title = "Product 10"
                        },
                        new
                        {
                            Id = "573b6192-8980-4775-856e-74ed0af99ae6",
                            Description = "Product 11 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/11/500",
                            Price = 11000L,
                            Title = "Product 11"
                        },
                        new
                        {
                            Id = "4559a953-6575-4a36-92d8-eb4f2d6988ca",
                            Description = "Product 12 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/12/500",
                            Price = 12000L,
                            Title = "Product 12"
                        },
                        new
                        {
                            Id = "0925bbe7-bde5-40c6-b6b5-2d95cd1bddc9",
                            Description = "Product 13 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/13/500",
                            Price = 13000L,
                            Title = "Product 13"
                        },
                        new
                        {
                            Id = "54745717-e183-4ddc-b42a-d0f9f70a7b7e",
                            Description = "Product 14 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/14/500",
                            Price = 14000L,
                            Title = "Product 14"
                        },
                        new
                        {
                            Id = "8d05cbef-0afc-4892-8f93-56988891d645",
                            Description = "Product 15 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/15/500",
                            Price = 15000L,
                            Title = "Product 15"
                        },
                        new
                        {
                            Id = "cf9c0f0d-2e66-488a-aa5d-ed3a1db0d4fe",
                            Description = "Product 16 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/16/500",
                            Price = 16000L,
                            Title = "Product 16"
                        },
                        new
                        {
                            Id = "b03a183a-a1aa-41a5-91ee-6e23964ab652",
                            Description = "Product 17 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/17/500",
                            Price = 17000L,
                            Title = "Product 17"
                        },
                        new
                        {
                            Id = "7041de9f-aa61-41bc-9f40-0c2ef865f297",
                            Description = "Product 18 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/18/500",
                            Price = 18000L,
                            Title = "Product 18"
                        },
                        new
                        {
                            Id = "f4c18335-370e-4217-a721-71aae51d94f7",
                            Description = "Product 19 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/19/500",
                            Price = 19000L,
                            Title = "Product 19"
                        },
                        new
                        {
                            Id = "9702dd1e-c35b-4bd9-b3f2-176ab325cb9d",
                            Description = "Product 20 description. This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/20/500",
                            Price = 20000L,
                            Title = "Product 20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
